### ISSUE TITLE
Scorovnik / tuning problem (virtual voltage undershoot)

### ISSUE THREAD

**Issue by vogelscheiss** [koralfx/Koralfx-Modules#11]
Having an issue with Scorovnik. Tunings unfortunately are off, i.e. flat.

Please see the image below. 
C4 lands at 0.98V instead of 1V.
C5 lands at 1.97V instead of 2V.
G3 lands at 0.57V instead of 0.58V

Compare with results from AS ReNote module, where the same tunings output 1V, 2V, and 0.58V respectively.

![image](https://user-images.githubusercontent.com/38222883/39535478-0527632c-4e02-11e8-92d1-afc8757b51b8.png)

Could this be fixed? It's cutting down considerably on the usability of what's otherwise a great module.  Thanks!

--Chuck

**Comment by koralfx** [comment]
Fixed in 0.6.9
