### ISSUE TITLE
request: Mixovnik solo/mute all on/off

### ISSUE THREAD

**Issue by davephillips** [koralfx/Koralfx-Modules#12]
Greetings ! I'm a great fan of Mixovnik, but there are a few things I'd like to see added. Above all, I'd like a couple of buttons to turn on/off *all* muted or solo'd channels. I realize that a button for "all channels solo on" is a little odd but it might be useful in some situations. Toggling mute/solo status across the mixer might have some other neat possibilities, for example, change all mutes to solo and vice-versa (for A/B comparison of mix channels). Just some ideas for future expansion. Keep up the great work ! :)

**Comment by koralfx** [comment]
Maybe in the future when I use soft buttons instead of physical ones, which themselves can not change the state.
