### ISSUE TITLE
Scorovnik

### ISSUE THREAD

**Issue by NikolaiVChr** [koralfx/Koralfx-Modules#13]
What does Audition mean?

Is Legato the same as slide?

Thank you for a great sequencer. :)

**Comment by NikolaiVChr** [comment]
Okay, found out Audition means that you hear the notes when you manipulate note sliders.
And legato means the gate out is active only very shortly at start of each note.

Super sequencer.

**Comment by therealkitman** [comment]
Hi,
I would argue the legato definition. Legato has no 'rest' between notes/steps. Staccato is more like having the gate open for shorter times than normal notes.

[Legato](https://en.wikipedia.org/wiki/Legato)
[Staccato](https://en.wikipedia.org/wiki/Staccato)

Regards.
