### ISSUE TITLE
Presetovnik cv input behaviour problem

### ISSUE THREAD

**Issue by sirthomassmith** [koralfx/Koralfx-Modules#15]
Hi Tomek!
First of all thanks for the great modules!

Without cv inputs, the indicators and the graphical knobs behave correctly. If I use the CV input, the indicator changes directly, and the graphical knob just not moves, which is a problem.
I think the cv input must change the knob position, not the indicator directly. (same way like how it works without cv input)
With the actual behaviour, I just cannot save presets, what I made with physical midi controller knobs.
If this behaviour is per design, would be nice to extend this module with a mode switch, to enable to store the cv values also.
Cheers
Tamas

**Comment by koralfx** [comment]
Hey. The knobs are not motorized. As in reality. The CV inputs work in direct mode. This is the idea of this project.
