### ISSUE TITLE
Link Button Behavior

### ISSUE THREAD

**Issue by jonheal** [koralfx/Koralfx-Modules#4]
A Question: It seems that the Link buttons bypass Solo button behavior. Is that true? If so, I think it might be more intuitive if you disabled the Solo buttons on channels where the Link button is active. I know there isn't a hardware equivalent for "disabling a button," but if you were to gray them out, I think it would be more intuitive what is happening.

Unless I have completely misunderstood what's going on here ...

**Comment by Coirt** [comment]
Doesn't link just link L/R channels? So when you move one side the other moves. Have not tried it out but gathered that is what it does.

**Comment by koralfx** [comment]
In the link mode, the left channel controls the loudness, mute and solo. Other things can be controlled. I thought about it also turning on the right button solo and mute, but after all it's a physical button, just like the slider is not motorized ;-).
Maybe in the next versions I will switch to the touch buttons. Then they will be able to light and extinguish any solo and mute lights.
