### ISSUE TITLE
Proposed new tags (for post 0.5.8)

### ISSUE THREAD

**Issue by DomiKamu** [koralfx/Koralfx-Modules#5]
Hi,

Tag story again (lol) there three lines I'll propose for future release (post 0.5.8), if you'll want.
For Quantovnik, quantizer isn't appropriate (it's a pitch quantizer, not a MIDI-like quantizer), so the nearest appropriate seems Effects + Utility (you'll can combine them).
MIXER_TAG if fine for Mixovnik (it was my suggestion on Facebook couple of days ago, you've applied it).
About your new "Beatovnik", it's mainly a clock modulator, but this tag doesn't exist in 0.5.1 (it exists in 0.6 however, you'll can use it when you'll port to 0.6), instead you'll can use CLOCK_TAG (it's a clock-based tool), like I've done for mine KlokSpid and RKD modules. Avoid UTILITY_TAG, it's for very basic modules, at very last resort!

p->addModel(createModel<QuantovnikWidget>("KoralfxVCV", "Quantovnik", "Quantovnik", EFFECT_TAG, UTILITY_TAG));
p->addModel(createModel<MixovnikWidget>("KoralfxVCV", "Mixovnik", "Mixovnik", MIXER_TAG));
p->addModel(createModel<BeatovnikWidget>("KoralfxVCV", "Beatovnik", "Beatovnik", CLOCK_TAG));

Cheers.
Dominique.

**Comment by koralfx** [comment]
Thank you for your next suggestions. The changes will be in the next versions.
