### ISSUE TITLE
Change name to not include "VCV"

### ISSUE THREAD

**Issue by AndrewBelt** [koralfx/Koralfx-Modules#7]
The VCV name is trademarked https://github.com/VCVRack/Rack#licenses and can't be used in unofficial products. It needs to be removed from the "author" name of the plugin, and I would highly recommend that the slug is changed as well. Better to do it earlier while the adoption is low rather than later. This is to prevent confusion with official VCV plugins and avoid diluting the brand. Perhaps change to KoralFX?

**Comment by koralfx** [comment]
Thank you for the information and I apologize for the oversight. Of course, I will do it in the next commit.

**Comment by AndrewBelt** [comment]
Much thanks!

**Comment by koralfx** [comment]
Andrew, is it also necessary to change the name of the repository?

**Comment by AndrewBelt** [comment]
Not really, but for organization, it would match the new slug name.
GitHub automatically places redirects to the git repos, so it should work without changing the `git remote origin` URL.
