### ISSUE TITLE
Mixovnik sometimes crashes rack when being deleted

### ISSUE THREAD

**Issue by darloth** [koralfx/Koralfx-Modules#8]
I have no reliable reproduction steps, sorry.

Sometimes when I delete a Mixovnik, especially after actually interacting with it (patching cables, twiddling knobs) Rack crashes. I believe it was an access violation crash, and will try to reproduce it to get you something more useful.

I am using version 0.6.1a-win binaries on rack version 6.0

**Comment by darloth** [comment]
It is possible this is a rack bug exacerbated by Mixovnik's truly amazing amount of knobs and controls - I've had similar crashes when deleting other modules, but only sometimes and much less often.

Regardless, this happens most with Mixovnik so I'll leave this issue open unless I can confirm - it might be two separate issues, it might not.

**Comment by DomiKamu** [comment]
Most modules cause crash (random) when you use "Del" key, but no crash from "Delete" (context menu). Are crashes occurs on "Del" key usage?
